### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ippee/zlitefetch#3]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by ichi-h** [comment]
Thanks for finding this plugin!  
I've added the MIT license, so please use it if you like.
